---
title: "KOGO_QC1(DropletUtils)"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=F, message=F)
```

### **Library**
```{r}
library(devtools)
library(Seurat)
library(scRNAseq)
library(scater)
library(harmony)
library(DropletUtils)
library(scran)
```

```{r, echo=FALSE}
rdatadir = "C:/Users/user/Desktop/대학원/2022_KOGO/rdata/"
plotdir = "C:/Users/user/Desktop/대학원/2022_KOGO/plots/"
ranaldir = "C:/Users/user/Desktop/대학원/2022_KOGO/R_analysis/"
```

### **Load Data**
```{r}
rawsce_1 <- read10xCounts(paste0(rdatadir, "20094_0001_A_B/raw_feature_bc_matrix"), type = "sparse", compressed = TRUE)
rawsce_2 <- read10xCounts(paste0(rdatadir, "20094_0002_A_B/raw_feature_bc_matrix"), type = "sparse", compressed = TRUE)
rawsce_3 <- read10xCounts(paste0(rdatadir, "20094_0003_A_B/raw_feature_bc_matrix"), type = "sparse", compressed = TRUE)
rawsce_4 <- read10xCounts(paste0(rdatadir, "20094_0004_A_B/raw_feature_bc_matrix"), type = "sparse", compressed = TRUE)
rawsce_5 <- read10xCounts(paste0(rdatadir, "20094_0005_A_B/raw_feature_bc_matrix"), type = "sparse", compressed = TRUE)
rawsce_6 <- read10xCounts(paste0(rdatadir, "20094_0006_A_B/raw_feature_bc_matrix"), type = "sparse", compressed = TRUE)
rawsce_7 <- read10xCounts(paste0(rdatadir, "20094_0007_A_B/raw_feature_bc_matrix"), type = "sparse", compressed = TRUE)
rawsce_8 <- read10xCounts(paste0(rdatadir, "20094_0008_A_B/raw_feature_bc_matrix"), type = "sparse", compressed = TRUE)
rawsce_9 <- read10xCounts(paste0(rdatadir, "20094_0009_A_B/raw_feature_bc_matrix"), type = "sparse", compressed = TRUE)
rawsce_12 <- read10xCounts(paste0(rdatadir, "20094_0012_A_B/raw_feature_bc_matrix"), type = "sparse", compressed = TRUE)
```

### **Check Data**
```{r}
rawsce_1
```

### **Run DropletUtils**
```{r}
rawsce_list <- c('rawsce_1', 'rawsce_2', 'rawsce_3', 'rawsce_4', 'rawsce_5',
                 'rawsce_6', 'rawsce_7', 'rawsce_8', 'rawsce_9', 'rawsce_12')

for (i in 1:length(rawsce_list)) {
  rawsce <- get(rawsce_list[i])
  
  br.out <- barcodeRanks(counts(rawsce))
  
  setwd(paste0(plotdir, 'DropletUtils'))
  png(paste0('DropletUtils_', rawsce_list[i], '.png'))
  
  plot(br.out$rank, br.out$total, log = "xy", xlab = "Rank", ylab = "Total", main = rawsce_list[i])
  
  o <- order(br.out$rank)
  lines(br.out$rank[o], br.out$fitted[o], col = "red")
  
  set.seed(2022)
  e.out <- emptyDrops(counts(rawsce))  ## Cells that have UMI counts lower than 100 are empty cells.
  table(Sig=e.out$FDR <= 0.05, Limited=e.out$Limited)
  is.cell <- e.out$FDR <= 0.05
  
  print(sum(is.cell, na.rm=TRUE))
  print(table(br.out$rank == sum(is.cell, na.rm=TRUE)))
  
  abline(h=min(br.out$fitted[o], na.rm=TRUE), col="red", lty=2)
  abline(h=metadata(br.out)$knee, col="dodgerblue", lty=2)
  abline(h=metadata(br.out)$inflection, col="forestgreen", lty=2)
  legend("bottomleft", lty=2, col=c("dodgerblue", "forestgreen", "red"), legend=c("knee", "inflection", "FDR_0.05"))
  dev.off()
  
  colnames(rawsce) = colData(rawsce)$Barcode
  rawsce <- rawsce[,which(e.out$FDR <= 0.05)]
  
  assign(paste0('DropletUtils_', rawsce_list[i]), rawsce)
}

```

### **Check DropletUtils data**
```{r}
DropletUtils_rawsce_1
```
